@baseUrl = http://localhost:5174/api/v1/products/

@id = 2

### Read all products
GET {{baseUrl}}

### Read product from ID
GET {{baseUrl}}/{{id}}

### Create a new product
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Adoration of the Magi",
  "price": 10000000,
  "quantity": 1
}

### Update a product info data
PUT {{baseUrl}}/{{id}}
Content-Type: application/json

{
  "name": "Self-portrait",
  "price": 9500000,
  "quantity": 1
}


### Delete a product
DELETE {{baseUrl}}/{{id}}